fprintf('&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&\n')
fprintf('&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&\n')
fprintf('&&                                                                       &&\n')
fprintf('&&    M M M M                 M M M M     C C C C C C C C C C C C C C    &&\n')                                                                                                                                                                           
fprintf('&&    M M M M M             M M M M M     C C C C C C C C C C C C C C    &&\n')                                                                                                          
fprintf('&&      M M  M M           M M  M M       C C                     C C    &&\n')                                                                                   
fprintf('&&      M M   M M         M M   M M       C C                     C C    &&\n')                                                                                    
fprintf('&&      M M    M M       M M    M M       C C                            &&\n')                                                                                 
fprintf('&&      M M     M M     M M     M M       C C                            &&\n')                                                                                  
fprintf('&&      M M      M M   M M      M M       C C                            &&\n')                                                                                  
fprintf('&&      M M       M M M M       M M       C C                            &&\n')                                                                                  
fprintf('&&      M M        M M M        M M       C C                            &&\n')                                                                                                                                                              
fprintf('&&      M M                     M M       C C                            &&\n')               
fprintf('&&      M M                     M M       C C                     C C    &&\n')              
fprintf('&&      M M                     M M       C C                     C C    &&\n')             
fprintf('&&    M M M M                 M M M M     C C C C C C C C C C C C C C    &&\n')                                   
fprintf('&&    M M M M                 M M M M     C C C C C C C C C C C C C C    &&\n')                                    
fprintf('&&                                                                       &&\n')
fprintf('&&  Departamento de Mecanica Computacional del Instituto Tecnologico de  &&\n')
fprintf('&&                             Buenos Aires                              &&\n')
fprintf('&&                                                                       &&\n')
fprintf('&&  Direccion de proyecto  : D''hers,      Sebastian                      &&\n')
fprintf('&&                                                                       &&\n')
fprintf('&&  Codigo desarrollado por: Medina,      Pablo                          &&\n')
fprintf('&&                           Jin,         Manuel                         &&\n')
fprintf('&&                           Moine,       Maria                          &&\n')
fprintf('&&                           Mujica Buj,  Juan Martin                    &&\n')
fprintf('&&                           Eiff,        Joaquin                        &&\n')
fprintf('&&                                                                       &&\n')
fprintf('&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&\n')
fprintf('&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&\n')                                                                    